### ISSUE TITLE
upgrade all packages for full support of null-safety

### ISSUE THREAD

**Issue by lucmichalski** [limcheekin/fluwix#58] opened 2022-01-22 18:53 UTC
Hi @limcheekin ,

Hope you are all well ! and happy new year !

I was playing with your great project and one thing that was obvious to me is that you should maybe upgrade all packages for full null-safety support

What do you think about that ?

Cheers,
Luc

**Comment by limcheekin** [comment] 2022-01-23 02:32
Hi there,

Thanks for raising the issue. I aware that some of the modules of the project is not migrated to null-safety yet, hence the project is not sound null-safety. In fact, issue #1 is keep track the migration works. Back then one of the dependency of a module is https://pub.dev/packages/charts_flutter, hence I put the migration works on hold until charts_flutter migrated to null-safety then I continue the migration works of the project.

The charts_flutter is now null-safety, however my work priority was shifted to blockchain development few months ago, please find out more at https://limcheekin.blogspot.com/2021/07/closing-gap.html. 

Hence, I will resume the work here only when I need to work on Flutter project, will close this issue as it is duplicate of issue #1.

**Closed by limcheekin** 2022-01-23 02:32 UTC
Labels: duplicate

**Comment by limcheekin** [comment] 2022-03-08 07:50
The app is now sound null safety :)
